apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opip-dev
resources:
  - ../../base
  - namespace.yaml
images:
  - name: harbor.cloudgenius.ca/opip/opip-api
    newTag: main
  - name: harbor.cloudgenius.ca/opip/opip-frontend
    newTag: main
patches:
  - target:
      kind: Ingress
      name: opip
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: opip-dev.example.com
