apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opip-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/globalcloudgenius/cloudgenius-opip-gitops.git
    targetRevision: main
    path: apps/opip/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: opip-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
